wandb_version: 1

batch_size:
  desc: null
  value: 100
N_input:
  desc: null
  value: 20
N_output:
  desc: null
  value: 20
gamma:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1765324075
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
